### ISSUE TITLE
generateWordPairs Always Return random string

### ISSUE THREAD

**Issue by VB10** [filiph/english_words#10]
Hello
I'm try generateWordPairs().elementAt(0) but this have problem so always return random value.

I need always same generateWordPairs().elementAt(0).
How can I do it?

Thank u
Best Regards

**Comment by tsmith1024** [comment]
It looks like if you provide a Random() to generateWordPairs you can set a consistent seed for that Random so you can get the same results every time.

Something like...
```dart
const seed = 1;
const rand = Random(seed);
const pair = generateWordPairs(rand).elementAt(0);
```

It's been a while on this one so you may have already gotten this figured out, but if not, I hope that helps!

**Comment by VB10** [comment]
@tsmith1024 thank u but have problem. It's enough for now. We talk after.
