### ISSUE TITLE
Version 3.0.0 does not exists on pub

### ISSUE THREAD

**Issue by febs** [filiph/english_words#13]
I am trying to exactly install version 3.0.0 with

`  english_words: 3.0.0
`

But:

> Running "flutter pub get" in xyloph...                          
> Because xyloph depends on english_words 3.0.0 which doesn't match any versions, version solving failed.
> pub get failed (1)

**Comment by filiph** [comment]
Hi @febs, that's an embarrassing ommission. I'm not sure if I can fix it (i.e. does pub.dev allow "filling in" versions from before). 

Any reason why not to use the newer version, 3.1.5? Even better, just do `english_words: ^3.0.0` and you will get non-breaking patches every time you `flutter packages upgrade`.

**Comment by febs** [comment]
Thank you @filiph for your reply. 
Yes I am aware that by using `^3.0.0` I'd get the latest 3.x version. 
I was just studying the pub packaging system though, I chose this package to experiment with and I found that bug. So I thought I had to report it. If that's not fixable then nevermind.
I came across a similar issue with another package which I forgot about afterwards so maybe it's quite common - although odd? 🤔

**Comment by filiph** [comment]
Ah, I understand. It’s every package owner’s decision which versions to publish. If I remember correctly, I saw a deficiency (if not a downright bug) in ’3.0.0’ as soon as I tagged it and uploaded to github (but before I pushed it to pub. dev). So it made the most sense to just up the version number and not to publish ’3.0.0’ to pub. dev.

In general, I think it’s valid to have some version numbers that never make it to pub. dev. You can specify other places where to publish your packages (like git or path), and it makes sense to have “in between” versions there.

Hope that clarifies this. I’ll close the bug but feel free to reopen at any time.
